# ==================================
# PersistentVolume para Sesiones WhatsApp (NFS)
# IMPORTANTE: Cambiar IP del servidor NFS
# ==================================

apiVersion: v1
kind: PersistentVolume
metadata:
  name: whatsapp-sessions-pv
  namespace: whatsapp-masivo
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany  # CRÍTICO: Permite múltiples pods leyendo/escribiendo
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.100  # ⚠️ CAMBIAR: IP de tu servidor NFS
    path: /mnt/nfs/whatsapp-sessions  # ⚠️ CAMBIAR: Ruta en el servidor NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whatsapp-sessions-pvc
  namespace: whatsapp-masivo
spec:
  accessModes:
    - ReadWriteMany  # CRÍTICO para compartir sesiones
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: whatsapp-sessions-pv

