apiVersion: v1
kind: Service
metadata:
  name: whatsapp-redis
  namespace: whatsapp-masivo
  labels:
    app: whatsapp-redis
spec:
  type: ClusterIP
  selector:
    app: whatsapp-redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: whatsapp-masivo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard  # Cambiar según tu cluster
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatsapp-redis
  namespace: whatsapp-masivo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatsapp-redis
  template:
    metadata:
      labels:
        app: whatsapp-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --appendonly
        - "yes"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whatsapp-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc

