apiVersion: v1
kind: Secret
metadata:
  name: whatsapp-secrets
  namespace: whatsapp-masivo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: whatsapp_root_2025_CHANGE_THIS
  MYSQL_PASSWORD: whatsapp_pass_2025_CHANGE_THIS
  JWT_SECRET: change_this_jwt_secret_in_production_min_32_chars
  SESSION_SECRET: change_this_session_secret_in_production_min_32_chars
  REDIS_PASSWORD: ""

